#ifndef ENUMS_H
#define ENUMS_H

typedef enum _DMI_MODULE_TYPE_
{
    DMI_BIOS,
    DMI_BASEBOARD,
    DMI_ENCLOSURE,
    DMI_CPU,
    DMI_CACHE,
    DMI_MEMORY_DEVICE
}DMIModuleType;

typedef enum _MENU_OPTIONS_IDS_
{
    COMPUTER_DEVICE_MANAGER_ID,
    COMPUTER_DMI_ID,
    COMPUTER_POWER_MANAGEMENT_ID,
    COMPUTER_SENSORS_ID,

    MOTHERBOARD_CPU_ID,
    MOTHERBOARD_SPD_ID,
    MOTHERBOARD_VIDEO_CARD_ID,

    OPERATING_SYSTEM_SUMMARY_ID,
    OPERATING_SYSTEM_PROCESSES_ID,
    OPERATING_SYSTEM_SYSTEM_DRIVERS_ID,
    OPERATING_SYSTEM_USERS_ID,

    STORAGE_ATA_ID,
    STORAGE_SMART_ID,

    NETWORK_DEVICES_ID,
    NETWORK_CONNECTIONS_ID,

    SOFTWARE_APPLICATION_MANAGER_ID,
    SOFTWARE_STARTUP_APPLICATIONS_ID
}MenuOptionId;

#define MENU_OPTION_ID_TAG              Qt::UserRole + 1
#define ATA_HDD_ID_TAG                  Qt::UserRole + 2

#endif // ENUMS_H
