#ifndef ENUMS_H
#define ENUMS_H

typedef enum _MODULE_TYPE_
{
    COMPUTER_DMI,
    COMPUTER_POWER_MANAGEMENT,
    HDD_HDD_INFORMATION,
    OS_OPERATING_SYSTEM,
    OS_PROCESSES,
    OS_SYSTEM_DRIVERS,
    STORAGE_SMART,
    SMBIOS_ENTRY_POINT,
    SOFTWARE_APPLICATION_MANAGER,
    SOFTWARE_STARTUP_APPLICATIONS
}ModuleType;

typedef enum _DMI_MODULE_TYPE_
{
    DMI_BIOS,
    DMI_BASEBOARD,
    DMI_CPU,
    DMI_MEMORY_DEVICE
}DMIModuleType;

#endif // ENUMS_H
